from typing import List, Optional
from pydantic import BaseModel, Field

class UserQuery(BaseModel):
    """User query to the agent."""
    question: str = Field(..., description="The user's natural-language question.")
    session_id: Optional[str] = Field(
        default=None, 
        description="Session ID; used later for personalization."
    )

class AgentAnswer(BaseModel):
    """Answer generated by the agent."""
    explanation: str = Field(..., description="Main explanation.")
    bullet_summary: List[str] = Field(
        default_factory=list,
        description="Key takeaways as bullet points."
    )
    model_name: Optional[str] = Field(
        default=None,
        description="LLM model name used.."
    )

class LLMMessage(BaseModel):
    """Message sent to the LLM."""
    role: str
    content: str

